stages:
  - qualite

qualite-php:
  image: lephare/php:7.2
  stage: qualite
  before_script:
    - composer global require hirak/prestissimo --no-interaction --no-progress --no-suggest
    - composer validate
    - composer install --prefer-dist --no-interaction --no-progress --no-suggest --dev
  script:
    - composer run lint:php-cs-fixer
    - composer run lint:phpstan