language: php
php:
  - '7.2'

stages:
  - qualite
  - name: build
    if: branch = master

jobs:
  include:
    - stage: qualite
      before_script:
        - composer global require hirak/prestissimo --no-interaction --no-progress --no-suggest
        - composer validate
        - composer install --prefer-dist --no-interaction --no-progress --no-suggest --dev
      script:
        - composer run lint:php-cs-fixer
        - composer run lint:phpstan
jobs1:
  include:
    - stage: build
      script:
        - composer global require hirak/prestissimo --no-interaction --no-progress --no-suggest
        - composer require --dev bamarni/composer-bin-plugin
        - composer bin box require --dev humbug/box
        - vendor/bin/box compile
  addons:
    artifacts:
      paths:
        - hug.phar